# -*- coding: utf-8 -*-
questionario = {
    'titolo': 'Indagine sul parco macchine utensili e sistemi di produzione per la lavorazione dei metalli al 31 Dicembre 2014',
    'elementi': [
        { 'classe': 'intestazione', 'testo': "Dati anagrafici dell'azienda" },
        { 'classe': 'input', 'testo': "Nome dell'azienda", 'numero': '1.1', 'tipo': 'text', 'required': True },
        { 'classe': 'input', 'testo': "Nome del compilatore", 'numero': '1.2', 'tipo': 'text', 'required': True },
        { 'classe': 'input', 'testo': "Struttura societaria", 'numero': '1.3', 'tipo': 'radio', 'scelte': ['azienda singola', 'azienda che possiede altre aziende', 'aziende parte di un gruppo'], 'required': True },
        { 'classe': 'input', 'testo': "Stabilimento/Unita locale", 'numero': '1.6', 'tipo': 'text', 'required': True},
        { 'classe': 'input', 'testo': "Indirizzo", 'numero': '1.7', 'tipo': 'text', 'required': True },
        { 'classe': 'input', 'testo': "Addetti dello stabilimento/Unita locale al 31/12/2014", 'numero': '1.8', 'tipo': 'number', 'required': True},
        { 'classe': 'input', 'testo': "Attivita principale dello stabilimento", 'numero': '1.9', 'tipo': 'text', 'required': True },
        { 'classe': 'input', 'testo': "Codice ATECO 2007", 'numero': '1.9b', 'tipo': 'text', 'required': True },
        { 'classe': 'input', 'testo': "Descrizione Codice ATECO 2007", 'numero': '1.9c', 'tipo': 'text', 'hidden': True},
        { 'classe': 'intestazione', 'testo': "Macchine utensili installate presso lo stabilimento/unita' locale al 31/12/2014" },
        { 'classe': 'input', 'testo': "Numero totale di macchine utensili", 'numero': '1.10', 'tipo': 'number',  'readonly': True, 'help_text': 'Comprendono macchine utensili, robot, altri sistemi di produzione indicati nella sezione dei dati dettagliati.'},
        { 'classe': 'input', 'testo': "macchine a controllo numerico", 'numero': '1.11', 'tipo': 'number', 'required': True },
        { 'classe': 'input', 'testo': "macchine convenzionali", 'numero': '1.12', 'tipo': 'number', 'required': True },
        { 'classe': 'intestazione', 'testo': "Vi preghiamo di indicare un indirizzo di posta elettronica, a cui invieremo lo studio" },
        { 'classe': 'input', 'testo': "Indirizzo email", 'numero': '1.13', 'tipo': 'email' },
        { 'classe': 'intestazione', 'testo': "Dati dettagliati per tipo di macchina" },
        { 'classe': 'griglia', 'griglia': {
            'gruppi_colonne': [
                { 'codice': '1', 'testo': 'Numero di macchine per periodo di installazione', 'numero_colonne': 5 },
                # { 'codice': '2', 'testo': '', 'numero_colonne': 1 },
                { 'codice': '3', 'testo': 'Numero di macchine per grado di automazione/integrazione', 'numero_colonne': 5, 'help_text': "Indicare il numero di macchine per ogni livello di automazione e integrazione" },
            ],
            'colonne': [
                { 'codice': '1.1', 'testo': 'Fino al 1994', 'sum_to': '2.1' },
                { 'codice': '1.2', 'testo': '1995 - 2004', 'sum_to': '2.1' },
                { 'codice': '1.3', 'testo': '2005 - 2009', 'sum_to': '2.1' },
                { 'codice': '1.4', 'testo': '2010 - 2014', 'sum_to': '2.1' },
                { 'codice': '2.1', 'testo': 'Totale', 'readonly': True, 'equal_to': '4.1' },
                { 'codice': '3.1', 'testo': 'Macc. singole', 'sum_to': '4.1' },
                { 'codice': '3.2', 'testo': '1^ livello', 'sum_to': '4.1', 'help_text': '<p><b>1° Livello</b></p>Macchine singole con sistema automatico di carico/scarico e movimentazione pezzi' },
                { 'codice': '3.3', 'testo': '2^ livello', 'sum_to': '4.1', 'help_text': '<p><b>2° Livello</b></p>Macchine integrate con altre macchine o impianti attraverso la gestione automatica di utensili/movimentazione' },
                { 'codice': '3.4', 'testo': '3^ livello', 'sum_to': '4.1', 'help_text': '<p><b>3° Livello</b></p>Macchine integrate con altre macchine o impianti attraverso reti informatiche di fabbrica e gestione produzione' },
                { 'codice': '4.1', 'testo': 'Totale', 'readonly': True, 'equal_to': '2.1' },
            ],
            'righe':[
                {'livello': '1', 'testo': 'MACCHINE UTENSILI AD ASPORTAZIONE', 'classe': 'intestazione'},
                {'livello': '2', 'testo': 'TORNI', 'classe': 'intestazione'},
                {'livello': '3', 'testo': 'Convenzionali', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Orizzontali', 'codice': '2.1', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Verticali', 'codice': '2.2', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Per assali, ruote montate', 'codice': '2.3', 'classe': 'domanda'},
                {'livello': '3', 'testo': 'A controllo numerico', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Orizzontali', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'diametro tornibile sulle guide: fino a 100 mm', 'codice': '2.4', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro tornibile sulle guide: da 101 a 250 mm', 'codice': '2.5', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro tornibile sulle guide: da 251 a 500 mm', 'codice': '2.6', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro tornibile sulle guide: da 501 a 800 mm', 'codice': '2.7', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro tornibile sulle guide: da 801 a 1.500 mm', 'codice': '2.8', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro tornibile sulle guide: oltre 1.500 mm', 'codice': '2.9', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Verticali', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'diametro autocentrante fino a 200 mm', 'codice': '2.10', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro autocentrante da 201 a 630 mm', 'codice': '2.11', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro piattaforma da 631 a 2.000 mm', 'codice': '2.12', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro piattaforma da 2.001 a 4.000 mm', 'codice': '2.13', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro piattaforma da 4.001 a 6.000 mm', 'codice': '2.14', 'classe': 'domanda'},
                {'stile': '', 'testo': 'diametro piattaforma oltre 6.000 mm', 'codice': '2.15', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Per assali, ruote montate', 'codice': '2.16', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'TRAPANI E FORATRICI', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Trapani', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'da banco', 'codice': '2.16b', 'classe': 'domanda'},
                {'stile': '', 'testo': 'a colonna e a torretta', 'codice': '2.17', 'classe': 'domanda'},
                {'stile': '', 'testo': 'radiali', 'codice': '2.18', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Foratrici', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'a mandrini multipli, per piastre tubiere', 'codice': '2.19', 'classe': 'domanda'},
                {'stile': '', 'testo': 'per fori profondi', 'codice': '2.20', 'classe': 'domanda'},
                {'stile': '', 'testo': 'per piastre e profilati', 'codice': '2.20b', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'FRESATRICI E ALESATRICI', 'classe': 'intestazione'},
                {'livello': '3', 'testo': 'Convenzionali', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Fresatrici', 'codice': '2.21', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Macchine per lavorazione di profilati leggeri', 'codice': '2.22', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre fresatrici convenzionali', 'codice': '2.23', 'classe': 'domanda'},
                {'livello': '3', 'testo': 'A controllo numerico', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Alesatrici (solo con fuso mandrino)', 'codice': '2.24', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Fresatrici', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'a montante fisso', 'codice': '2.25', 'classe': 'domanda'},
                {'stile': '', 'testo': 'a montante mobile', 'codice': '2.26', 'classe': 'domanda'},
                {'stile': '', 'testo': 'a portale', 'codice': '2.27', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Fresa-alesatrici', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'a montante fisso', 'codice': '2.28', 'classe': 'domanda'},
                {'stile': '', 'testo': 'a montante mobile', 'codice': '2.29', 'classe': 'domanda'},
                {'stile': '', 'testo': 'a portale', 'codice': '2.30', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Macchine per lavorazione di profilati leggeri', 'codice': '2.31', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre fresatrici a controllo numerico', 'codice': '2.32', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'CENTRI DI LAVORO', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Verticali', 'classe': 'intestazione'},
                {'stile': '', 'testo': "con corsa dell'asse Y fino a 650 mm", 'codice': '2.33', 'classe': 'domanda'},
                {'stile': '', 'testo': "con corsa dell'asse Y superiore a 650 mm", 'codice': '2.34', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Orizzontali', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'fino a pallet 500 (ISO 8526-1)', 'codice': '2.35', 'classe': 'domanda'},
                {'stile': '', 'testo': 'da pallet 501 a 630 (ISO 8526-1)', 'codice': '2.36', 'classe': 'domanda'},
                {'stile': '', 'testo': 'da pallet 631 a 800 (ISO 8526-1)', 'codice': '2.37', 'classe': 'domanda'},
                {'stile': '', 'testo': 'da pallet 801 a 1.000 (ISO 8526-2)', 'codice': '2.38', 'classe': 'domanda'},
                {'stile': '', 'testo': 'da pallet 1.001 (ISO 8526-2)', 'codice': '2.39', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'MACCHINE TRANSFER', 'classe': 'intestazione'},
                {'livello': '3', 'testo': 'Convenzionali', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Lineari', 'codice': '2.40', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Circolari', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'ad asse verticale', 'codice': '2.41', 'classe': 'domanda'},
                {'stile': '', 'testo': 'ad asse orizzontale (a tamburo)', 'codice': '2.42', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre macchine transfer', 'codice': '2.43', 'classe': 'domanda'},
                {'livello': '3', 'testo': 'A controllo numerico', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Lineari', 'codice': '2.44', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Circolari', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'ad asse verticale', 'codice': '2.45', 'classe': 'domanda'},
                {'stile': '', 'testo': 'ad asse orizzontale (a tamburo)', 'codice': '2.46', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre macchine transfer', 'codice': '2.47', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'RETTIFICATRICI', 'classe': 'intestazione'},
                {'livello': '3', 'testo': 'Convenzionali', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'In tondo', 'codice': '2.48', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Senza centri', 'codice': '2.49', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Per piani e profili', 'codice': '2.50', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Lapidelli', 'codice': '2.51', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre rettificatrici convenzionali', 'codice': '2.52', 'classe': 'domanda'},
                {'livello': '3', 'testo': 'A controllo numerico', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'In tondo', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'per interni', 'codice': '2.53', 'classe': 'domanda'},
                {'stile': '', 'testo': 'per esterni e universali', 'codice': '2.54', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Senza centri', 'codice': '2.55', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Per piani e profili', 'classe': 'intestazione'},
                {'stile': '', 'testo': "con capacita' di lavoro fino a 600*300 mm", 'codice': '2.56', 'classe': 'domanda'},
                {'stile': '', 'testo': "con capacita' di lavoro oltre 600*300 mm", 'codice': '2.57', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre rettificatrici a controllo numerico', 'codice': '2.58', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'AFFILATRICI', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Da officina', 'codice': '2.59', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Da produzione', 'codice': '2.60', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'MACCHINE PER RUOTE DENTATE', 'codice': '2.61', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'SEGATRICI, TRONCATRICI', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Segatrici a nastro', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'di peso da 101 a 900 kg', 'codice': '2.62', 'classe': 'domanda'},
                {'stile': '', 'testo': 'di peso da 901 a 2.000 kg', 'codice': '2.63', 'classe': 'domanda'},
                {'stile': '', 'testo': 'di peso da 2.001 a 4.000 kg', 'codice': '2.64', 'classe': 'domanda'},
                {'stile': '', 'testo': 'di peso da 4.001 a 6.000 kg', 'codice': '2.65', 'classe': 'domanda'},
                {'stile': '', 'testo': 'di peso superiore a 6.000 kg', 'codice': '2.66', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Segatrici circolari e troncatrici', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'di peso da 101 a 700 kg', 'codice': '2.67', 'classe': 'domanda'},
                {'stile': '', 'testo': 'di peso da 701 a 1.700 kg', 'codice': '2.68', 'classe': 'domanda'},
                {'stile': '', 'testo': 'di peso superiore a 1.700 kg', 'codice': '2.69', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'MACCHINE PER SUPERFINITURA', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'lappatrici per piani', 'codice': '2.70', 'classe': 'domanda'},
                {'stile': '', 'testo': 'lappatrici in tondo', 'codice': '2.71', 'classe': 'domanda'},
                {'stile': '', 'testo': 'altre macchine per superfinitura', 'codice': '2.72', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'MACCHINE PER RIPARAZIONE DI MOTORI E AUTOVEICOLI', 'codice': '2.73', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'MASCHIATRICI E FILETTATRICI', 'codice': '2.74', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'CENTRATRICI E INTESTATRICI', 'codice': '2.75', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'PANTOGRAFI, M. PER INCIDERE E DIVIDERE', 'codice': '2.76', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'SMUSSATRICI', 'codice': '2.77', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'BROCCIATRICI E STOZZATRICI', 'codice': '2.78', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'ALTRE MACCHINE UTENSILI AD ASPORTAZIONE', 'codice': '2.79', 'classe': 'domanda'},
                {'livello': '1', 'testo': 'MACCHINE UTENSILI A DEFORMAZIONE', 'classe': 'intestazione'},
                {'livello': '2', 'testo': 'MACCHINE PER FUCINARE ED ESTRUDERE', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'magli e forgiatrici', 'codice': '3.1', 'classe': 'domanda'},
                {'stile': '', 'testo': 'presse per stampaggio a caldo', 'codice': '3.2', 'classe': 'domanda'},
                {'stile': '', 'testo': 'macchine per estrusione dei metalli', 'codice': '3.3', 'classe': 'domanda'},
                {'stile': '', 'testo': 'altre macchine per lavorazioni a caldo', 'codice': '3.4', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'MACCHINE PER PIEGATURA E CURVATURA', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Presse piegatrici verticali', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'con larghezza lavorabile fino a 2,5 metri', 'codice': '3.5', 'classe': 'domanda'},
                {'stile': '', 'testo': 'con larghezza lavorabile da 2,51 a 4 metri', 'codice': '3.6', 'classe': 'domanda'},
                {'stile': '', 'testo': 'con larghezza lavorabile oltre 4 metri', 'codice': '3.7', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Pannellatrici', 'codice': '3.8', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Spianatrici e raddrizzatrici', 'codice': '3.8b', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Linee e macchine per profilatura', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'macchine per profilare', 'codice': '3.9', 'classe': 'domanda'},
                {'stile': '', 'testo': 'linee di profilatura', 'codice': '3.10', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Calandre', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'per spessori fino a 3 mm', 'codice': '3.11', 'classe': 'domanda'},
                {'stile': '', 'testo': 'per spessori oltre 3 mm', 'codice': '3.12', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre linee di lavorazione della lamiera', 'codice': '3.13', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Rifilatrici e bordatrici', 'codice': '3.14', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Presse piegatrici orizzontali', 'codice': '3.15', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Curvatrici per tubi', 'codice': '3.16', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Curvatrici per profilati', 'codice': '3.17', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre macchine per piegatura e curvatura', 'codice': '3.18', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'MACCHINE PER TAGLIO', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Cesoie a ghigliottina per lamiera', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'con larghezza lavorabile fino a 2,5 metri', 'codice': '3.19', 'classe': 'domanda'},
                {'stile': '', 'testo': 'con larghezza lavorabile da 2,51 a 4 metri', 'codice': '3.20', 'classe': 'domanda'},
                {'stile': '', 'testo': 'con larghezza lavorabile oltre 4 metri', 'codice': '3.21', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Linee di taglio della lamiera', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'in strisce/slitter', 'codice': '3.22', 'classe': 'domanda'},
                {'stile': '', 'testo': 'in fogli', 'codice': '3.23', 'classe': 'domanda'},
                {'stile': '', 'testo': 'linee combinate/bandellatrici', 'codice': '3.24', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Cesoie/intagliatrici e cesoie/punzonatrici', 'codice': '3.25', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Scantonatrici e tranciatrici', 'codice': '3.26', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre cesoie per lamiera', 'codice': '3.28', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Cesoie per tondini e billette', 'codice': '3.29', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'M. per taglio di piastre e profilati', 'codice': '3.30', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'MACCHINE PER PUNZONATURA', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Punzonatrici e centri di punzonatura', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'per spessori fino a 3 mm', 'codice': '3.31', 'classe': 'domanda'},
                {'stile': '', 'testo': 'per spessori oltre 3 mm', 'codice': '3.32', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Macchine combinate per punzonatura e taglio laser/plasma', 'codice': '3.33', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Presse per tranciatura fine', 'codice': '3.34', 'classe': 'domanda'},
                {'livello': '2', 'testo': "MACCHINE PER LA LAVORAZIONE DELLE ESTREMITA' DEI TUBI", 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'M. per mandrinatura', 'codice': '3.35', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'M. per conificazione', 'codice': '3.36', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'M. per filettatura', 'codice': '3.37', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': "Altre m. per lavorazione estremita' dei tubi", 'codice': '3.38', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'PRESSE', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Meccaniche', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'forza fino a 100 tonnellate', 'codice': '3.39', 'classe': 'domanda'},
                {'stile': '', 'testo': 'forza da 101 a 500 tonnellate', 'codice': '3.40', 'classe': 'domanda'},
                {'stile': '', 'testo': 'forza da 501 a 1.000 tonnellate', 'codice': '3.41', 'classe': 'domanda'},
                {'stile': '', 'testo': 'forza oltre 1.000 tonnellate', 'codice': '3.42', 'classe': 'domanda'},
                {'livello': '4', 'testo': 'Idrauliche/oledinamiche', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'forza fino a 200 tonnellate', 'codice': '3.43', 'classe': 'domanda'},
                {'stile': '', 'testo': 'forza da 201 a 750 tonnellate', 'codice': '3.44', 'classe': 'domanda'},
                {'stile': '', 'testo': 'forza da 751 a 2.000 tonnellate', 'codice': '3.45', 'classe': 'domanda'},
                {'stile': '', 'testo': 'forza oltre 2.000 tonnellate', 'codice': '3.46', 'classe': 'domanda'},
                {'stile': '', 'testo': 'per raddrizzare', 'codice': '3.47', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Presse elettriche/servopresse', 'codice': '3.48', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Presse pneumatiche, rivettatrici', 'codice': '3.49', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Presse e macchine per idroformatura', 'codice': '3.50', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre presse (comprese presse inverse)', 'codice': '3.51', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'MACCHINE PER FABBRICAZIONE VITI, BULLONI E DADI', 'codice': '3.52', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'MACCHINE PER LAVORAZIONE DEL FILO METALLICO', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'trafilatrici per filo metallico', 'codice': '3.53', 'classe': 'domanda'},
                {'stile': '', 'testo': 'macchine per molle', 'codice': '3.54', 'classe': 'domanda'},
                {'stile': '', 'testo': 'altre macchine per lavorazione del filo metallico', 'codice': '3.55', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'ALTRE MACCHINE A DEFORMAZIONE', 'codice': '3.56', 'classe': 'domanda'},
                {'livello': '1', 'testo': 'MACCHINE UTENSILI OPERANTI CON TECNOLOGIE NON CONVENZIONALI', 'classe': 'intestazione'},
                {'livello': '2', 'testo': 'A ELETTROEROSIONE', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'A filo', 'codice': '4.1', 'classe': 'domanda'},
                {'stile': '', 'testo': 'A tuffo', 'codice': '4.2', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'LASER', 'classe': 'intestazione'},
                {'livello': '4', 'testo': 'Per il taglio', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'della lamiera', 'codice': '4.3', 'classe': 'domanda'},
                {'stile': '', 'testo': 'di tubi e profilati', 'codice': '4.4', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Per microlavorazioni', 'codice': '4.5', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'TAGLIO AL PLASMA', 'codice': '4.8', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'TAGLIO WATERJET', 'codice': '4.9', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'ALTRE MACCHINE OPERANTI CON T.N.C', 'codice': '4.10', 'classe': 'domanda'},
                {'livello': '1', 'testo': 'ROBOT E BRACCI MECCANICI', 'classe': 'intestazione'},
                {'stile': 'label2', 'testo': 'BRACCI MECCANICI', 'codice': '5.1', 'classe': 'domanda'},
                {'stile': 'label2', 'testo': 'ROBOT A SEQUENZA', 'codice': '5.2', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'ROBOT A TRAIETTORIA CONTROLLATA', 'classe': 'intestazione'},
                {'stile': '', 'testo': 'articolati', 'codice': '5.3', 'classe': 'domanda'},
                {'stile': '', 'testo': 'cartesiani', 'codice': '5.4', 'classe': 'domanda'},
                {'stile': '', 'testo': 'scara', 'codice': '5.5', 'classe': 'domanda'},
                {'stile': '', 'testo': 'altri', 'codice': '5.6', 'classe': 'domanda'},
                {'livello': '1', 'testo': 'ALTRI SISTEMI DI PRODUZIONE', 'classe': 'intestazione'},
                {'livello': '2', 'testo': 'MACCHINE DI MISURA E PROVA', 'classe': 'intestazione'},
                {'livello': '3', 'testo': 'M. di misura convenzionali', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Macchine di misura a coordinate (CMM)', 'codice': '5.7', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre', 'codice': '5.8', 'classe': 'domanda'},
                {'livello': '3', 'testo': 'M. di misura controllo numerico', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Macchine di misura a coordinate (CMM)', 'codice': '5.9', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Macchine per il presetting degli utensili', 'codice': '5.11', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Macchine per equilibratura', 'codice': '5.12', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Altre macchine di controllo e misura', 'codice': '5.13', 'classe': 'domanda'},
                {'livello': '2', 'testo': 'MACCHINE E IMPIANTI PER TRATTAMENTI TERMICI E FINITURA', 'classe': 'intestazione'},
                {'stile': 'label4', 'testo': 'Trattamenti termici', 'codice': '5.14', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Trattamento e finitura superfici', 'codice': '5.15', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Impianti di lavaggio industriale', 'codice': '5.16', 'classe': 'domanda'},
                {'stile': 'label4', 'testo': 'Marcatrici', 'codice': '5.17', 'classe': 'domanda'},
            ]
        }},
        { 'classe': 'textarea', 'testo': "Note e commenti", 'numero': '6.1' }
    ]
}
__author__ = 'Vincenzo Petrungaro'

